name: Docker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  iterator:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'finder'
        run: echo "::set-output name=images::$(find . -type f -name Dockerfile | xargs dirname | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      images: '${{ steps.finder.outputs.images }}'

  publisher:
    runs-on: 'ubuntu-latest'
    needs: 'iterator'
    strategy:
      matrix:
        image: '${{ fromJson(needs.iterator.outputs.images) }}'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          submodules: 'recursive'
      - uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          IMAGE="ghcr.io/${{ github.actor }}/$(basename ${{ matrix.image }}):latest"
          IMAGE="$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"
          DOCKER_BUILDKIT=0 docker build --tag "${IMAGE}" '${{ matrix.image }}'
          docker push "${IMAGE}"
          
      
    
